import Head from "next/head";
import data from "../src/data";
import Content from "../src/Content";

export function getStaticProps() {
  return {
    props: {
      content: data,
    },
  };
}

export default function Home({ content }) {
  return (
    <>
      <Head>
        <title>Content Test</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Content content={content} />
      </main>
    </>
  );
}
